AWSTemplateFormatVersion: 2010-09-09
Description: The s3strm backend

Parameters:
  URLGeneratorCodeKey:
    Description: The S3 key where the URLGenerator code can be found
    Type: String
  RefeederCodeKey:
    Description: The S3 key where the Refeeder code can be found
    Type: String
  URLMinimumValidity:
    Description: The shortest allowable validity for a URL
    Type: Number
    Default: 14400    # 4 hours

Resources:
  URLGeneratorLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref URLGeneratorCodeKey
      Description: Generate a temporary URL for an IMDB ID
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
          URL_MINIMUM_VALIDITY: !Ref URLMinimumValidity
      FunctionName: s3strm-urlgenerator
      Handler: lambda.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 120
    DependsOn: Role

  RefeederLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref RefeederCodeKey
      Description: Regenerates metadata for an IMDB ID
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
          VIDEO_CREATED_TOPIC: !ImportValue s3strm-video-created-topic
      FunctionName: s3strm-refeeder
      Handler: lambda.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 120
    DependsOn: Role

  URLGeneratorInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:execute-api", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt URLGeneratorLambda.Arn

  RefeederInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:execute-api", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt RefeederLambda.Arn

  ApiGatewayStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      # TODO: Add an SSL certificate
      # ClientCertificateId: String
      DeploymentId: !Ref ApiGatewayDeployment
      Description: "Production"
      RestApiId: !Ref ApiGateway
      StageName: prod

  ApiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      Description: "Production"
      RestApiId: !Ref ApiGateway
    DependsOn:
      - MoviePosterGetMethod
      - MoviePosterPutMethod
      - MovieStreamMethod
      - MovieRefeedMethod

  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: s3strm front door
      Name: s3strm

  ApiMovieResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: "movie"
      RestApiId: !Ref ApiGateway

  ApiMovieImdbResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieResource
      PathPart: "{imdb_id}"
      RestApiId: !Ref ApiGateway

  ApiMovieStreamResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieImdbResource
      PathPart: "stream"
      RestApiId: !Ref ApiGateway

  MovieStreamMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          -
            ResponseParameters:
              "method.response.header.location": "integration.response.body.url"
            StatusCode: 302
        Type: AWS
        RequestTemplates:
          "application/json": "{ \"imdb_id\": \"$input.params('imdb_id')\" }\n"
        Uri: !Join [ "", [ "arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":lambda:path", "/2015-03-31/functions/", { "Fn::GetAtt": [ "URLGeneratorLambda", "Arn" ] }, "/invocations" ] ]
      MethodResponses:
        -
          ResponseParameters:
            method.response.header.location: True
          StatusCode: 302
      ResourceId: !Ref ApiMovieStreamResource
      RestApiId: !Ref ApiGateway

  ApiMoviePosterResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieImdbResource
      PathPart: poster
      RestApiId: !Ref ApiGateway

  MoviePosterGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      RequestParameters:
        method.request.path.imdb_id: true
      Integration:
        Credentials: !GetAtt Role.Arn
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - SelectionPattern: \d{3}
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Date: integration.response.header.Date
              method.response.header.Content-Length: integration.response.header.content-length
            StatusCode: 200
        Type: AWS
        RequestParameters:
          "integration.request.path.imdb_id": "method.request.path.imdb_id"
        Uri: !Join [ "", [ "arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":s3:path/", { "Fn::ImportValue": "s3strm-movies-bucket" }, "/{imdb_id}/poster.jpg" ] ]
      MethodResponses:
        -
          StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
            method.response.header.Date: true
      ResourceId: !Ref ApiMoviePosterResource
      RestApiId: !Ref ApiGateway

  MoviePosterPutMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: PUT
      RequestParameters:
        method.request.path.imdb_id: true
        method.request.header.Content-Type: true
        method.request.header.x-amz-acl: true
        method.request.header.Expect: true
      Integration:
        Credentials: !GetAtt Role.Arn
        IntegrationHttpMethod: PUT
        IntegrationResponses:
          - SelectionPattern: \d{3}
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Length: integration.response.header.content-length
            StatusCode: 200
        Type: AWS
        RequestParameters:
          integration.request.header.Content-Type: method.request.header.Content-Type
          integration.request.path.imdb_id: method.request.path.imdb_id
        Uri: !Join [ "", [ "arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":s3:path/", { "Fn::ImportValue": "s3strm-movies-bucket" }, "/{imdb_id}/poster-custom.jpg" ] ]
        PassthroughBehavior: "when_no_match"
      MethodResponses:
        -
          StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
      ResourceId: !Ref ApiMoviePosterResource
      RestApiId: !Ref ApiGateway

  ApiMovieRefeedResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieImdbResource
      PathPart: refeed
      RestApiId: !Ref ApiGateway

  MovieRefeedMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          -
            ResponseParameters:
              method.response.header.Date: integration.response.body.date
            StatusCode: 200
        Type: AWS
        RequestTemplates:
          "application/json": "{ \"imdb_id\": \"$input.params('imdb_id')\" }\n"
        Uri: !Join [ "", [ "arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":lambda:path", "/2015-03-31/functions/", { "Fn::GetAtt": [ "RefeederLambda", "Arn" ] }, "/invocations" ] ]
      MethodResponses:
        -
          ResponseParameters:
            method.response.header.Date: true
          StatusCode: 200
      ResourceId: !Ref ApiMovieRefeedResource
      RestApiId: !Ref ApiGateway

  ApiMovieKodiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieImdbResource
      PathPart: kodi
      RestApiId: !Ref ApiGateway

  ApiMovieKodiStrmResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ApiMovieKodiResource
      PathPart: strm
      RestApiId: !Ref ApiGateway

  MovieKodiStrmMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      RequestParameters:
        method.request.path.imdb_id: true
      Integration:
        Credentials: !GetAtt Role.Arn
        IntegrationHttpMethod: GET
        IntegrationResponses:
          - SelectionPattern: \d{3}
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Date: integration.response.header.Date
              method.response.header.Content-Length: integration.response.header.content-length
            StatusCode: 200
        Type: AWS
        RequestParameters:
          "integration.request.path.imdb_id": "method.request.path.imdb_id"
        Uri: !Join [ "", [ "arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":s3:path/", { "Fn::ImportValue": "s3strm-movies-bucket" }, "/{imdb_id}/kodi.strm" ] ]
      MethodResponses:
        -
          StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
            method.response.header.Date: true
      ResourceId: !Ref ApiMovieKodiStrmResource
      RestApiId: !Ref ApiGateway

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "s3strm-backend"
          PolicyDocument:
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: Allow
                Action: "s3:*"
                Resource: !Join [ "", [ "arn:aws:s3:::", !ImportValue s3strm-movies-bucket, "/*" ] ]
              -
                Effect: Allow
                Action: "s3:*"
                Resource: !Join [ "", [ "arn:aws:s3:::", !ImportValue s3strm-settings-bucket, "/*" ] ]
              -
                Effect: Allow
                Action: "sns:publish"
                Resource: !ImportValue s3strm-video-created-topic

Outputs:
  URLGeneratorLambda:
    Value: !GetAtt URLGeneratorLambda.Arn
